[build-system]
requires = ['metpy','numpy','matplotlib','datetime','siphon','hatchling']
build-backend = "hatchling.build"

[project]
name = "make_skew_t"
version = "0.0.1"
authors = [{ name="Matt Oehler", email="moehler@wisc.edu" }]
description = "A package for making skew-T diagrams"
readme = "README.md"
requires-python=">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent"]